---
# tasks file for roles/app-tier
  # installation of pacckages based on inventory groups
- name: Install firewalld
yum:
  name: firewalld
  stateL: latest

- name: Start firewalld service
  service:
   name: firewalld
   state: started
   enabled: true

- name: Install httpd
yum:
  name: "{{ item }}"
  stateL: latest
with_items:
  - "{{ httpd_pkg }}"

- name: Start httpd service
  service:
   name: "{{ httpd_srv }}"
   state: started
   enabled: true


- name: Copy vhost template file
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
  notify:
    - restart_httpd

- name: Create document root
  file:
    path: /var/www/vhost/
    state: directory

#- name: Copy index.j2 file
#  template:
#    src: index.j2
#    dest: /var/www/vhost/index.php
#    mode: 0644
#    owner: apache

- name: Open httpd port
  firewalld:
    service: http
    state: enabled
    immediate: true
    permanent: true

- name: Enable selinux boolean
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  loop:
    - httpd_can_network_connect_db
    - httpd_can_network_connect
